### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by robbieaverill** [Ziggeo/manifold-php-signature#4]
Sorry, one more thing @iglesiaspablo 😄 could you please add a license to this project when you have a chance?

**Comment by robbieaverill** [comment]
Bump @iglesiaspablo. Happy to make a PR if you let me know which one you're happy with

**Comment by iglesiaspablo** [comment]
Hi @robbieaverill! Sorry I missed this message. Added a License in the new tagged version v1.0.1 . Thanks for the comment!

**Comment by robbieaverill** [comment]
Thanks!!
